</div>
		<footer>
			<ul id="footer">
				<li><a href="index.php">Home</a></li>
				<li><a href="views/about.php">About us</a></li>
				<li><a href="views/contact.php">Contact us</a></li>
			</ul>
			<p id="echo">Site powered by:</br><a href="http://the.echonest.com">echonest.com</a></p>
		</footer>
		<script type="text/javascript" src="js/jquery-1.10.1.js"></script>
		<script type="text/javascript" src="js/main.js"></script>
	</body>
</html>