<header>
<nav id="home_nav">
	<h1>The Forum</h1>
	<ul>
		<li><a href="#">Login</a></li>
		<li><a href="#">Join</a></li>
		<input type="search" name="search" placeholder="Search Artist"/>
	</ul>
</nav>
</header>

<div id="typeExample">
	<h2 id="genres">Genres</h3>
	<ul>
		<li>HipHop</li>
		<li>Rock</li>
		<li>Indie</li>
		<li>Jazz</li>
	</ul>
</div><!-- ends typeExampl -->

<!-- The items in the following: 
	*Top Artist*
	*Top News*
	*Latest Reviews*
	Are All placeholders until I add the jquery to dynamically add/chage the content
 -->
<div id="topArtist">
	<h2 id="tArtist">Top Artist:</h2>
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
	<img width="#" height="#" class="topArtistPic" src="#">
</div><!-- ends top artist -->

<div id="topNews">
	<h2 id="topNewLabel">Latest Reviews:</h2>
	<article class="headline">
		<h3 class="headlineName">This is a Headline</h3>
		<p>This is a sample. This is a sample. This is a sample.</p>
	</article> <!-- Ends headline -->
</div> <!-- ends topNews -->

<div id="latesReviews">
	<h2 id="latestReviewsLabel">Latest Reviews:</h2>
	<article class="reviews">
		<img width="#" height="#" class="reviewPic" src="#">
		<p class="reviewExample">This is a sample. This is a sample. This is a sample.</p>
	</article> <!-- Ends headline -->
</div> <!-- ends topNews -->



	