<header>
<nav id="home_nav">
	<h1 id="logo"><a href="index.php">The Forum</a></h1>
	<p id="saying">Your Favorite Artist, All The Time.</p>
	<ul id="navItems">
		<li><a href="index.php">Home</a></li>
		<li><a href="views/login.php">Login</a></li>
		<li><a href="views/join.php">Join</a></li>
	</ul>
</nav>
</header>

	<div id="container">
<!-- The items in the following: 
	*Top Artist*
	*Top News*
	Are will be dynamically added with jquery -->
<div id="topArtist">
	<!--<h2 id="tArtist">Top Artist:</h2>-->
</div><!-- ends top artist -->

<div id="topNews">
</div> <!-- ends topNews -->




	