<header>
<nav id="home_nav">
	<h1><a href="index.php">The Forum</a></h1>
	<ul>
		<li><a href="views/login.php">Login</a></li>
		<li><a href="views/join.php">Join</a></li>
		<!--<input type="search" name="search" placeholder="Search Artist"/>-->
	</ul>
</nav>
</header>

<!--<div id="typeExample">
	<h2 id="genres">Genres</h3>
	<ul>
		<li>HipHop</li>
		<li>Rock</li>
		<li>Indie</li>
		<li>Jazz</li>
	</ul>
</div>--><!-- ends typeExampl -->

<!-- The items in the following: 
	*Top Artist*
	*Top News*
	*Latest Reviews*
	Are All placeholders until I add the jquery to dynamically add/chage the content
 -->
<div id="topArtist">
	<!--<h2 id="tArtist">Top Artist:</h2>-->
</div><!-- ends top artist -->

<div id="topNews">
</div> <!-- ends topNews -->

<!--<div id="latestReviews">
	<h2 id="latestReviewsLabel">Latest Reviews:</h2>
</div> --><!-- ends topNews -->



	